---
name: "BlockTranscoding"
guid: "55330139-1f8b-4e5d-a207-2afece96e7a6"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Block transcoding based on media resolution."
description: ""
category: "General"
owner: "lucapolesel"
artifacts:
- "BlockTranscoding.dll"
changelog: >
  changelog
